spring.cloud.stream.kafka.streams.binder.configuration.default:
  key.serde: org.apache.kafka.common.serialization.Serdes$StringSerde
  value.serde: org.apache.kafka.common.serialization.Serdes$StringSerde
spring.cloud.stream.bindings:
  output:
    destination: so0544out
#    producer:
#      useNativeEncoding: true
#    bufferSize: 1
#    configuration:
#      batch:
#        size: 1
  input:
    destination: so0544in
    group: so0544
#    consumer:
#      useNativeDecoding: true
